### ISSUE TITLE
Weird text/characters on console output

### ISSUE THREAD

**Issue by daryltucker** [slush0/stratum-mining-proxy#77]
2▮15↑▮3↑19 ▮1:5▮:36←▮88 INFO ⎻⎼⎺│≤ ⎽├⎼▒├┤└_┌☃⎽├e┼e⎼↓⎽┤b└☃├ # [138└⎽] S▒▒⎼e °⎼⎺└ 'd▒⎼≤┌├┤c┐e⎼↓°⎼▒┼┐┬▒☃├e' ▒cce⎻├ed← d☃°° 2▮8

Any ideas why stuff is showing up like this in my tmux console?

My miner sees the following now, quite often, as well:

    Pool 0 is sending mismatched block contents to us (0 is not 256-511)

Thanks.

**Comment by solf233** [comment]
no idea

**Comment by slush0** [comment]
No idea. I see this for first time.

**Comment by daryltucker** [comment]
I restarted the script and it became much clearer:

    2015-03-20 20:46:51,205 WARNING protocol protocol.dataReceived # Failed message: Cannot decode message '??N??????\??K:4?U?k??0?,?(?$?' from xx.xx.xx.xx)

The client that connected was bfgminer 5.1.0-34-ga0fb134.
