### ISSUE TITLE
Mointor Usage ?

### ISSUE THREAD

**Issue by DarrenRainey** [slush0/stratum-mining-proxy#83]
is there an api or website code to monitor the  amount of connections and worker names etc

**Comment by ab1jx** [comment]
![lcp](https://cloud.githubusercontent.com/assets/3131978/25256240/6c72b82a-25fd-11e7-94c8-077bd90957d9.gif)
Depends on the pool I guess.  There are some apps for phones for monitoring too.

**Comment by DarrenRainey** [comment]
Yeah I know I can monitor it at the pool but I was wondering if there was a way I could monitor it at the proxy level

**Comment by ab1jx** [comment]
Well, technically, it *is* open source, you can make whatever changes you want.  Just watch out they don't get clobbered if it auto-updates.  My guess is not everybody would want the same changes.  I'd like to see it rewritten in proper C, I'm not a Python fan at all.  I'd probably want to stuff events into a database, but which one?  Probably PostgreSQL.  Certainly a GUI could be written around it, but I'm reasonably happy with just a terminal window open to it.  I see:
[prsnap.txt](https://github.com/slush0/stratum-mining-proxy/files/948965/prsnap.txt)
In a GUI I'd  probably have icons for workers that change color depending on their state, something like that.  Maybe a box on the screen showing different parameters for each worker.  But the GUI would have to be portable to different operating systems, and I don't want to think about trying to support it.  The 3 Android monitors I've tried all just take the HTML API link to pool data and show it in a box, so I saved it as a bookmark to my home screen, I can just tap it on my phone and see what's not running.  And with litecoinpool.org you also get current exchange rates in that data, I suspect trading's probably more profitable than mining.
